export enum PRODUCT {
  PROMOTION_CAROUSEL = 12,
  RECOMMEND_HOW_MANY = 20,
  POPULAR = 20,
  RECOMMEND_POINT = 4,
  LAST_PRODUCT_CACHE_TIME = 60 * 60 * 1000,
  CRON_INTERVAL = 30 * 1000,
  CRON_TAKE = 100,
}

export const LAST_PRODUCT_CACHE_KEY = 'LAST_PRODUCT_CACHE_KEY';
