export enum QUEUE_NAME {
    AUTH = 'AUTH_QUEUE',
    PRODUCT = 'PRODUCT_QUEUE',
    CART = 'CART_QUEUE'
}

export enum SERVICE_NAME {
    AUTH_SERVICE = 'AUTH_SERVICE',
    PRODUCT_SERVICE = 'PRODUCT_SERVICE',
    CART_SERVICE = 'CART_SERVICE',
}

export enum SERVICE_MESSAGE {
    VALIDATE_JWT = 'VALIDATE_JWT',
    GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
}